name: Add GitHub Release Tag

on:
  push:
    branches:
      - main # 根据实际分支名修改（如 master）
    paths:
      - '**' # 监控所有文件变更（可根据需要调整）

jobs:
  release:
    # if: github.repository == '@huberyyang/todo-scripts'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整 Git 历史记录

      - name: Extract version from commit message
        id: extract-version
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ $COMMIT_MSG =~ [cC]hore:\ release\ (v[0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION=${BASH_REMATCH[1]}
            echo "Detected version: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "No release version detected in commit message."
            exit 0  # 非发版提交，跳过后续步骤
          fi

      - name: Create Git tag
        if: steps.extract-version.outputs.version != ''
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag -a ${{ steps.extract-version.outputs.version }} -m "Release ${{ steps.extract-version.outputs.version }}"
          git push origin ${{ steps.extract-version.outputs.version }}

      - name: Create GitHub Release
        if: steps.extract-version.outputs.version != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用默认 Token
        with:
          tag_name: ${{ steps.extract-version.outputs.version }}
          release_name: ${{ steps.extract-version.outputs.version }}
          body: |
            **Release Notes**
            - Auto-generated by GitHub Actions
          draft: false
          prerelease: false
